### ISSUE TITLE
[Slock only] [client specific] pam_usb causes pam module to crash

### ISSUE THREAD

**Issue by DhruvaSambrani** [mcdope/pam_usb#141]
I use slock as a screen lock with a pam_auth patch which allows me to use Arch Linux's `login` to authenticate me. When pam_usb is installed, I can unlock if my usb is connected. 

However, if the usb is not connected, and 2 consecutive pam attempts are made, the pam module seems to crash, further crashing slock, allowing an "unlock". Below is the text printed

```
❯ sudo -u dhruva slock
* Authentication request for user "dhruva" (login)
* Authentication device "Key" is connected.
* Performing one time pad verification...
* Access granted.

# Unplug USB

❯ sudo -u dhruva slock
* Authentication request for user "dhruva" (login)
* Authentication device "Key" is not connected.
* Access denied.
slock: Authentication failure
* Authentication request for user "dhruva" (login)

(process:627502): GLib-GObject-WARNING **: 15:01:02.846: cannot register existing type 'UDisksClient'

(process:627502): GLib-GObject-CRITICAL **: 15:01:02.851: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:627502): GLib-GObject-CRITICAL **: 15:01:02.851: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:627502): GLib-CRITICAL **: 15:01:02.851: g_once_init_leave: assertion 'result != 0' failed

(process:627502): GLib-GIO-CRITICAL **: 15:01:02.851: g_initable_new_valist: assertion 'G_TYPE_IS_INITABLE (object_type)' failed

(process:627502): libudisks2-CRITICAL **: 15:01:02.851: udisks_client_get_object_manager: assertion 'UDISKS_IS_CLIENT (client)' failed
[1]    627501 segmentation fault  sudo -u dhruva slock
```

**Comment by DhruvaSambrani** [comment]
Further, if no authentication device is configured for a user, then this error does not occur, and the screen remains locked

**Comment by mcdope** [comment]
Thanks for reporting,  esp. since it's finally something new and not the
usual localness crap :D

My first impression would be that slock seems to keep the pam modules
loaded, which other PAM clients usually don't. pam_usb basicly expects to
be cleanly initialized on each usage if I'm not wrong.

I'm at work right now, but will check this right when I get home since it
is pretty much security relevant. In case you are in need of secure screen
lock and don't want to replace slock i would highly recommend to disable
pam_usb for now.



Am Di., 19. Juli 2022 um 11:34 Uhr schrieb Dhruva Sambrani <
***@***.***>:

**Comment by mcdope** [comment]
I've just pushed the branch `issue-141-crash-with-slock`, this will for sure not fix your issue - but will help me massivly locate the location where exactly we cause that crash. 

Would be nice if you could build from that branch, try again and post the output again. Guess I know where it is, but want to be sure.

**Comment by DhruvaSambrani** [comment]
Also i don't know if this was intended, but slock's authentication fails even with the usb plugged in.

```
❯ slock
* Authentication request for user "dhruva" (login)
* Authentication device "Key" is connected.
* Performing one time pad verification...
* Access granted.
slock: Authentication failure
* Authentication request for user "dhruva" (login)

(process:885450): GLib-GObject-WARNING **: 21:25:13.568: cannot register existing type 'UDisksClient'

(process:885450): GLib-GObject-CRITICAL **: 21:25:13.574: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:885450): GLib-GObject-CRITICAL **: 21:25:13.574: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:885450): GLib-CRITICAL **: 21:25:13.574: g_once_init_leave: assertion 'result != 0' failed

(process:885450): GLib-GIO-CRITICAL **: 21:25:13.574: g_initable_new_valist: assertion 'G_TYPE_IS_INITABLE (object_type)' failed

(process:885450): libudisks2-CRITICAL **: 21:25:13.574: udisks_client_get_object_manager: assertion 'UDISKS_IS_CLIENT (client)' failed
[1]    885450 segmentation fault (core dumped)  slock
❯ pamusb-check dhruva
* Authentication request for user "dhruva" (pamusb-check)
* Authentication device "Key" is connected.
* Performing one time pad verification...
* Access granted.
```

**Comment by mcdope** [comment]
Sorry, my bad - forgot to told you need to enable `<option name="debug">true</option>` either global or for your user. 

But with that option enabled you should see something like "Entering someFunctionName()" followed by the crash.

That is doesn't work with the usb plugged in doesn't surprise me considering the error. This is almost to be expected since UDisks, which is used to enumerate and access the media is the thing causing the crash.

**Comment by DhruvaSambrani** [comment]
```
❯ sudo -u dhruva slock
* Authentication request for user "dhruva" (login)
[src/local.c:210] deny_remote is disabled. Skipping local check.
[src/device.c:079] Entering pusb_device_check()
[src/device.c:031] Entering pusb_device_connected()
[src/device.c:039] Searching for "Key2" in the hardware database...
* Authentication device "Key2" is not connected.
* Access denied.
slock: Authentication failure
* Authentication request for user "dhruva" (login)
[src/local.c:210] deny_remote is disabled. Skipping local check.
[src/device.c:079] Entering pusb_device_check()

(process:1113663): GLib-GObject-WARNING **: 03:47:49.433: cannot register existing type 'UDisksClient'

(process:1113663): GLib-GObject-CRITICAL **: 03:47:49.435: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:1113663): GLib-GObject-CRITICAL **: 03:47:49.435: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(process:1113663): GLib-CRITICAL **: 03:47:49.435: g_once_init_leave: assertion 'result != 0' failed

(process:1113663): GLib-GIO-CRITICAL **: 03:47:49.435: g_initable_new_valist: assertion 'G_TYPE_IS_INITABLE (object_type)' failed
[src/device.c:031] Entering pusb_device_connected()

(process:1113663): libudisks2-CRITICAL **: 03:47:49.435: udisks_client_get_object_manager: assertion 'UDISKS_IS_CLIENT (client)' failed
[1]    1113662 segmentation fault  sudo -u dhruva slock
```

**Comment by mcdope** [comment]
Nice thanks! 

Fix incoming in the next two days

**Comment by mcdope** [comment]
Hmmm... not so sure this is really caused by pam_usb. Seems it's only triggered by `slock`. The [udisks docs](http://storaged.org/doc/udisks2-api/latest/UDisksClient.html#udisks-client-new-sync) says all one need to do to clean the previous is to `g_object_unref()` it, which pam_usb is already doing. 

I've just pushed another commit into that branch which should at least gracefully catch the error and exit properly so slock doesn't crash. 

Could also be caused by running slock via sudo, since that messes with tty detection / env vars. 

Guess for a proper fix we will have till Oracle gets its ass up and finally updates VirtualBox for current kernel so I can repro in a VM...

**Comment by DhruvaSambrani** [comment]
I pulled the latest commit, but it still crashes slock with a segfault

**Comment by DhruvaSambrani** [comment]
To reproduce my setup, 
1. Install Manjaro 
1. `git clone https://git.suckless.org/slock`
1. `curl -#LO https://tools.suckless.org/slock/patches/pam_auth/slock-pam_auth-20190207-35633d4.diff`
1. `cd slock`
1. `git apply -3 ../slock-pam_auth-20190207-35633d4.diff`
1. `sed "s/nobody/$USER/g;s/nogroup/$USER/g" -i config.def.h`
1. `make`
1. `sudo make install`
2. `slock`

**Comment by mcdope** [comment]
Thanks for the repro instructions! Very helpful (and often forgotten...)

A quick glance at that patch makes me wonder if the slock code is explicitly looking for "Password: " in the output, because of this lines:

```
+		if (msg[i]->msg_style == PAM_PROMPT_ECHO_OFF &&
+				strncmp(msg[i]->msg, "Password: ", 10) == 0) {
```

If that really is the case, this will never work. But that's just the very first impression, will try to repro tomorrow.

**Comment by DhruvaSambrani** [comment]
Hi @mcdope I've since switched from slock to i3lock which works absolutely fine with pam_usb! if you are sure this is a slock issue, or if the ifx is too complex, please go ahead and close this/make it low priority 😄

**Comment by DhruvaSambrani** [comment]
I don't remember, but considering that I don't know what that is, I think it was not set. Note that PAMUSB worked properly apart from the slock usecase

**Comment by mcdope** [comment]
Thanks!



Am Mi., 22. März 2023 um 18:42 Uhr schrieb Dhruva Sambrani <
***@***.***>:
